import type { Metadata } from 'next';
import { Lexend, Source_Serif_4 } from 'next/font/google';
import './globals.css';

const lexend = Lexend({
  subsets: ['latin'],
  variable: '--lexend',
});

const sourceSerif4 = Source_Serif_4({
  subsets: ['latin'],
  variable: '--sourceSerif4',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lexend.variable} ${sourceSerif4.variable}`}>
      <body>{children}</body>
    </html>
  );
}
